import Head from "next/head";
import styles from "../styles/Home.module.css";
import client from "../client";
import Card from "../components/Card";
import Hero from "../components/Hero";


export default function Home({ post, details }) {
  console.log(post);
  console.log(details);
  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Hero
          detailsTitle={details[0].title}
          detailInfo={details[0].description}
        />
        <Card
          title="Recent Posts"
          postTitle={post[0].title}
          postTitle1={post[1].title}
          postTitle2={post[2].title}
        />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const details = await client.fetch(
    `*[_type == "details"] | order(_createdAt desc)`
  );
  const post = await client.fetch(
    `*[_type == "post"] | order(_createdAt desc)`
  );
  return {
    props: {
      post,
      details,
    },
  };
}
