import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createClient } from "next-sanity";


const client = createClient({
  projectId: "eltl721x",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false
});



export default function Home({animals}) {
  console.log(animals)

  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h2>{animals[0].name} its a {animals[0].type}</h2>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const animals = await client.fetch(`*[_type == "animal"]`);

  return {
    props: {
      animals
    }
  };
}
